Supermercado/Models/Genero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Supermercado.Models {
    public class Genero {
        public int Id { get; set; }
        [Display(Name = "Gênero")]
        public String Nome { get; set; }
    }
}

Supermercado/Controllers/GenerosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Supermercado.AcessoDados;
using Supermercado.Models;
using System.Linq.Dynamic;

namespace Supermercado.Controllers
{
    
    public class GenerosController : Controller
    {
        private readonly BancoContexto _db = new BancoContexto();

        // GET: Generos
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Listar(string searchPhrase, int current = 1, int rowCount = 5)
        {
            var chave = Request.Form.AllKeys.First(k => k.StartsWith("sort"));
            var ordenacao = Request[chave];
            var campo = chave.Replace("sort[", string.Empty).Replace("]", string.Empty);
            var generos = _db.Generos.ToList();

            var total = generos.Count();

            if (!string.IsNullOrWhiteSpace(searchPhrase))
            {            
                generos = generos.FindAll(g => g.Nome.ToLower().Contains(searchPhrase.ToLower()));
            }

            string campoOrdenacao = $"{campo} {ordenacao}";

            var generosPaginados = generos.OrderBy(campoOrdenacao).Skip((current - 1) * rowCount).Take(rowCount);

            return Json(new
            {
                rows = generosPaginados.ToList(),
                current,
                rowCount,
                total
            }
            , JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genero genero = _db.Generos.Find(id);
            if (genero == null)
            {
                return HttpNotFound();
            }
            return PartialView(genero);
        }

      

        // GET: Generos/Create
        public ActionResult Create()
        {
            return PartialView();
        }
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Genero genero)
        {
            if (ModelState.IsValid)
            {
                _db.Generos.Add(genero);
                _db.SaveChanges();
                return Json(new { resultado = true, message = "Genero cadastrado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }
        }

        // GET: Generos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genero genero = _db.Generos.Find(id);
            if (genero == null)
            {
                return HttpNotFound();
            }
            return PartialView(genero);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Genero genero)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(genero).State = EntityState.Modified;
                _db.SaveChanges();

                return Json(new { resultado = true, message = "Genero editado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }
        }

        // GET: Generos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genero genero = _db.Generos.Find(id);
            if (genero == null)
            {
                return HttpNotFound();
            }
            return PartialView(genero);
        }

        // POST: Generos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            try
            {
                Genero genero = _db.Generos.Find(id);

                _db.Generos.Remove(genero);

                _db.SaveChanges();

                return Json(new { resultado = true, message = "Genero excluído com sucesso" });
            }
            catch (Exception e)
            {
                return Json(new { resultado = false, message = e.Message });
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Supermercado/Views/Generos/Create.cshtml
@model Supermercado.Models.Genero
    
@{
    ViewBag.Title = "Novo Genero";
}

<h2><span class="glyphicon glyphicon-plus"></span> @ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Create", "Generos", FormMethod.Post, new { id = "formCrud" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">


        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Nome)
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group">
        <input type="button" value="Salvar" class="btn btn-primary btn-lg" />
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

Supermercado/Views/Generos/Delete.cshtml
@model Supermercado.Models.Genero

@{
    ViewBag.Title = "Apagar";
}

<h2><span class="glyphicon glyphicon-remove"></span> @ViewBag.Title Genero</h2>
<hr />
<h3>Confirma a exclução esse game?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>


    @using (Html.BeginForm($"Delete", $"Generos", FormMethod.Post, new { id = "formCrud" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="button" value="Confirmar" class="btn btn-danger" />
        </div>
    }
</div>

<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

Supermercado/Views/Generos/Details.cshtml
@model Supermercado.Models.Genero

@{
    ViewBag.Title = "Detalhamento";
}

<h2><span class="glyphicon glyphicon-list"></span> Detalhamento</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>
</div>

Supermercado/Views/Generos/Edit.cshtml
@model Supermercado.Models.Genero

@{
    ViewBag.Title = "Editar genero";
}

<h2><span class="glyphicon glyphicon-edit"></span> @ViewBag.Title</h2>
<hr />


@using (Html.BeginForm("Edit", "Generos", FormMethod.Post, new { id = "formCrud" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="row">
        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Nome)
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>

    </div>

    <div class="form-group">
        <input type="button" value="Confirmar" class="btn btn-primary btn-lg" />
    </div>
}


@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

Supermercado/Views/Generos/Index.cshtml
@{
    ViewBag.Title = "Listar Generos";
}

<p>
    <a href="javascript:void(0)" data-action="Create" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Novo Genero
    </a>
</p>

<table id="gridDados" class="table table-striped">
    <thead>
        <tr>
            <th data-column-id="Nome" data-order="asc">Nome</th>    
            <th data-formatter="Acoes" data-sortable="false">Ações</th>
        </tr>
    </thead>
</table>

@section scripts{

    <script src="~/Scripts/toastr.js"></script>
    @Scripts.Render("~/bundles/jquerybootgrid")
    <script src="~/Scripts/projeto/ControlarGrid.js"></script>

    <script type="text/javascript">

        numeral.language("pt-br");

        var controller = "Generos";

        var urlListar = "@Url.Action($"Listar")";

        $(document).ready(configurarControles);

    </script>

}

@section estilos{

    <link href="~/Content/jquery.bootgrid.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
}