Supermercado/Controllers/FilmesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Supermercado.AcessoDados;
using Supermercado.Models;
using System.Linq.Dynamic;
using System.Collections.Generic;
using System;

namespace Supermercado.Controllers
{
    public class FilmesController : Controller
    {
        private readonly BancoContexto _db = new BancoContexto();

        // GET: Filme
        public ActionResult Index()
        {
            // var filmes = _db.Filme.Include(g => g.Genero);
            // return View(filmes.ToList());
            return View();
        }

        public JsonResult Listar(string searchPhrase, int current = 1, int rowCount = 5)
        {
            var chave = Request.Form.AllKeys.First(k => k.StartsWith("sort"));
            var ordenacao = Request[chave];
            var campo = chave.Replace("sort[", string.Empty).Replace("]", string.Empty);
            var filmes = _db.Filmes.Include(l => l.Genero);

            var total = filmes.Count();

            if (!string.IsNullOrWhiteSpace(searchPhrase))
            {
                int ano;
                int.TryParse(searchPhrase, out ano);

                decimal valor;
                decimal.TryParse(searchPhrase, out valor);
                filmes = filmes.Where("Titulo.Contains(@0) OR Diretor.Contains(@0) OR AnoLancamento == @1 OR Valor = @2", searchPhrase, ano, valor);
            }

            string campoOrdenacao = $"{campo} {ordenacao}";

            var filmesPaginados = filmes.OrderBy(campoOrdenacao).Skip((current - 1) * rowCount).Take(rowCount);

            return Json(new
            {
                rows = filmesPaginados.ToList(),
                current,
                rowCount,
                total
            }
            , JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Filme game = _db.Filmes.Include(l => l.Genero).FirstOrDefault(l => l.Id == id.Value);
            // game = _db.Filme.Include(l => l.Tipo).FirstOrDefault(l => l.Id == id.Value);

            if (game == null)
            {
                return HttpNotFound();
            }

            return PartialView(game);
        }
        // GET: Filme/Create
        public ActionResult Create()
        {
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome");
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Filme game)
        {
            var tipos = _db.Tipos.ToList();
            var tipo = tipos.Find(tipo1 => tipo1.Nome.Contains("Filme"));
            game.Tipo = tipo;
            game.TipoId = tipo.Id;
            if (ModelState.IsValid)
            {
                _db.Filmes.Add(game);
                _db.SaveChanges();
                return Json(new { resultado = true, message = "Filme cadastrado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }

        }

        // GET: Filme/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Filme game = _db.Filmes.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", game.GeneroId);
            return PartialView(game);
        }

        // POST: Filme/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Filme game)
        {
            var tipos = _db.Tipos.ToList();
            var tipo = tipos.Find(tipo1 => tipo1.Nome.Contains("Filme"));
            game.Tipo = tipo;
            game.TipoId = tipo.Id;
            if (ModelState.IsValid)
            {
                _db.Entry(game).State = EntityState.Modified;
                _db.SaveChanges();

                return Json(new { resultado = true, message = "Filme editado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }
        }

        // GET: Filme/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Filme game = _db.Filmes.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return PartialView(game);
        }

        // POST: Filme/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            try
            {
                Filme game = _db.Filmes.Find(id);

                _db.Filmes.Remove(game);

                _db.SaveChanges();

                return Json(new { resultado = true, message = "Filme excluído com sucesso" });
            }
            catch (Exception e)
            {
                return Json(new { resultado = false, message = e.Message });
            }


        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Supermercado/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Supermercado.AcessoDados;
using Supermercado.Models;
using System.Linq.Dynamic;

namespace Supermercado.Controllers
{
    public class GamesController : Controller
    {
        private readonly BancoContexto _db  = new BancoContexto();

        // GET: Games
        public ActionResult Index()
        {
           // var games = _db.Games.Include(g => g.Genero);
           // return View(games.ToList());
            return View();
        }

        public JsonResult Listar(string searchPhrase, int current = 1, int rowCount = 5)
        {
            var chave = Request.Form.AllKeys.First(k => k.StartsWith("sort"));
            var ordenacao = Request[chave];
            var campo = chave.Replace("sort[", string.Empty).Replace("]", string.Empty);
            var games = _db.Games.Include(l => l.Genero);

            var total = games.Count();

            if (!string.IsNullOrWhiteSpace(searchPhrase))
            {
                int ano;
                int.TryParse(searchPhrase, out ano);

                decimal valor;
                decimal.TryParse(searchPhrase, out valor);
                games = games.Where("Titulo.Contains(@0) OR Plataforma.Contains(@0) OR AnoLancamento == @1 OR Valor = @2", searchPhrase, ano, valor);
            }

            string campoOrdenacao = $"{campo} {ordenacao}";

            var gamesPaginados = games.OrderBy(campoOrdenacao).Skip((current - 1) * rowCount).Take(rowCount);

            return Json(new
            {
                rows = gamesPaginados.ToList(),
                current,
                rowCount,
                total
            }
            , JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Game game = _db.Games.Include(l => l.Genero).FirstOrDefault(l => l.Id == id.Value);
            // game = _db.Games.Include(l => l.Tipo).FirstOrDefault(l => l.Id == id.Value);

            if (game == null)
            {
                return HttpNotFound();
            }

            return PartialView(game);
        }
        // GET: Games/Create
        public ActionResult Create()
        {
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome");
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Game game)
        {
            var tipos = _db.Tipos.ToList();
            var tipo = tipos.Find(tipo1 => tipo1.Nome.Contains("Game"));
            game.Tipo = tipo;
            game.TipoId = tipo.Id;
            if (ModelState.IsValid)
            {
                _db.Games.Add(game);
                _db.SaveChanges();
                return Json(new { resultado = true, message = "Game cadastrado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }

        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = _db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", game.GeneroId);
            return PartialView(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Game game)
        {
            var tipos = _db.Tipos.ToList();
            var tipo = tipos.Find(tipo1 => tipo1.Nome.Contains("Game"));
            game.Tipo = tipo;
            game.TipoId = tipo.Id;
            if (ModelState.IsValid)
            {
                _db.Entry(game).State = EntityState.Modified;
                _db.SaveChanges();

                return Json(new { resultado = true, message = "Game editado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = _db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return PartialView(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            try
            {
                Game game = _db.Games.Find(id);

                _db.Games.Remove(game);

                _db.SaveChanges();

                return Json(new { resultado = true, message = "Game excluído com sucesso" });
            }
            catch (Exception e)
            {
                return Json(new { resultado = false, message = e.Message });
            }


        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Supermercado/Views/Shared/_Layout.cshtml
s<!DOCTYPE html>
@using Resources
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CRUD</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("estilos", false)

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">@Resources.Site.NomeLoja</a>
            </div>
            <ul class="nav navbar-nav">
               
                          
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@Resources.Site.Admin<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink(@Resources.Site.Livros, "Index", "Livros")</li>
                        <li>@Html.ActionLink(@Resources.Site.Jogos, "Index", "Games")</li>
                        <li>@Html.ActionLink(@Resources.Site.Filmes, "Index", "Filmes")</li>
                        <li>@Html.ActionLink(@Resources.Site.Figuras, "Index", "ActionFigures")</li>
                        <li>@Html.ActionLink(@Resources.Site.Mangas, "Index", "Mangas")</li>
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink(@Resources.Site.Generos, "Index", "Generos")</li>
                        <li>@Html.ActionLink(@Resources.Site.Lojas, "Index", "LojasFisicas")</li>
                        <li>@Html.ActionLink("Loja fisicas Azure", "Index", "LojaFisicas")</li>
                    </ul>
                </li>
                  
               
                <li>@Html.ActionLink(@Resources.Site.About, "About", "Home")</li>
                <li>@Html.ActionLink(@Resources.Site.WebMail, "Index", "WebMail")</li>


                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@Resources.Site.Idioma<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="~/Home/Ingles">@Resources.Site.IN</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="~/Home/Portugues">@Resources.Site.PT</a></li>
                    </ul>
                </li>
</ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CRUD</p>
        </footer>
    </div>

    <div class="modal fade" id="minhaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div id="conteudoModal"></div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>