Supermercado/Models/Manga.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Supermercado.Models
{
    public class Manga
    {
        public int Id { get; set; }

        [Display(Name = "Título")]
        public string Titulo { get; set; }

        public string Autor { get; set; }

        public int Ano { get; set; }
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        public decimal Valor { get; set; }

        [Display(Name = "Gênero")]
        public int GeneroId { get; set; }
        public Genero Genero { get; set; }
        [Display(Name = "Tipo")]
        public int TipoId { get; set; }
        public Tipo Tipo { get; set; }
    }
}

Supermercado/Controllers/MangasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Supermercado.AcessoDados;
using Supermercado.Models;
using System.Linq.Dynamic;

namespace Supermercado.Controllers
{
    public class MangasController : Controller
    {
        private BancoContexto _db = new BancoContexto();

        // GET: Mangas
        public ActionResult Index()
        {
            //var mangas = _db.Mangas.Include(m => m.Genero).Include(m => m.Tipo);
            //return View(mangas.ToList());
            return View();
        }

        public JsonResult Listar(string searchPhrase, int current = 1, int rowCount = 5)
        {
            var chave = Request.Form.AllKeys.First(k => k.StartsWith("sort"));
            var ordenacao = Request[chave];
            var campo = chave.Replace("sort[", string.Empty).Replace("]", string.Empty);
            var mangas = _db.Mangas.Include(l => l.Genero);

            var total = mangas.Count();

            if (!string.IsNullOrWhiteSpace(searchPhrase))
            {
                int ano;
                int.TryParse(searchPhrase, out ano);

                decimal valor;
                decimal.TryParse(searchPhrase, out valor);
                mangas = mangas.Where("Titulo.Contains(@0) OR Autor.Contains(@0) OR Ano == @1 OR Valor = @2", searchPhrase, ano, valor);
            }

            string campoOrdenacao = $"{campo} {ordenacao}";

            var mangasPaginados = mangas.OrderBy(campoOrdenacao).Skip((current - 1) * rowCount).Take(rowCount);

            return Json(new
            {
                rows = mangasPaginados.ToList(),
                current,
                rowCount,
                total
            }
            , JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Manga manga = _db.Mangas.Include(l => l.Genero).FirstOrDefault(l => l.Id == id.Value);
            // manga = _db.Mangas.Include(l => l.Tipo).FirstOrDefault(l => l.Id == id.Value);

            if (manga == null)
            {
                return HttpNotFound();
            }

            return PartialView(manga);
        }
        // GET: Mangas/Create
        public ActionResult Create()
        {
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome");
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Manga manga)
        {
            var tipos = _db.Tipos.ToList();
            var tipo = tipos.Find(tipo1 => tipo1.Nome.Contains("Manga"));
            manga.Tipo = tipo;
            manga.TipoId = tipo.Id;
            if (ModelState.IsValid)
            {
                _db.Mangas.Add(manga);
                _db.SaveChanges();
                return Json(new { resultado = true, message = "Manga cadastrado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }

        }

        // GET: Mangas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manga manga = _db.Mangas.Find(id);
            if (manga == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", manga.GeneroId);
            return PartialView(manga);
        }

        // POST: Mangas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Manga manga)
        {
            var tipos = _db.Tipos.ToList();
            var tipo = tipos.Find(tipo1 => tipo1.Nome.Contains("Manga"));
            manga.Tipo = tipo;
            manga.TipoId = tipo.Id;
            if (ModelState.IsValid)
            {
                _db.Entry(manga).State = EntityState.Modified;
                _db.SaveChanges();

                return Json(new { resultado = true, message = "Manga editado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }
        }

        // GET: Mangas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manga manga = _db.Mangas.Find(id);
            if (manga == null)
            {
                return HttpNotFound();
            }
            return PartialView(manga);
        }

        // POST: Mangas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            try
            {
                Manga manga = _db.Mangas.Find(id);

                _db.Mangas.Remove(manga);

                _db.SaveChanges();

                return Json(new { resultado = true, message = "Manga excluído com sucesso" });
            }
            catch (Exception e)
            {
                return Json(new { resultado = false, message = e.Message });
            }


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Supermercado/Views/Mangas/Create.cshtml
@model Supermercado.Models.Manga

@{
    ViewBag.Title = "Novo manga";
}

<h2><span class="glyphicon glyphicon-plus"></span> @ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Create", "Mangas", FormMethod.Post, new { id = "formCrud" }))
{
    <div class="container-fluid">
        <div class="form-horizontal">
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GeneroId, "GeneroId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
                </div>
            </div>

            <<div class="form-group">
                <input type="button" value="Salvar" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>
}


@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

Supermercado/Views/Mangas/Delete.cshtml
@model Supermercado.Models.Manga

@{
    ViewBag.Title = "Apagar";
}

<h2><span class="glyphicon glyphicon-remove"></span> @ViewBag.Title Livro</h2>
<hr />
<h3>Confirma a exclução esse livro?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Mangas", FormMethod.Post, new { id = "formCrud" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="button" value="Confirmar" class="btn btn-danger" />
        </div>
    }
</div>

<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

Supermercado/Views/Mangas/Details.cshtml
@model Supermercado.Models.Manga

@{
    ViewBag.Title = "Detalhamento";
}

<h2><span class="glyphicon glyphicon-list"></span> Detalhamento</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>
</div>

Supermercado/Views/Mangas/Edit.cshtml
@model Supermercado.Models.Manga


@{
    ViewBag.Title = "Editar manga";
}

<h2><span class="glyphicon glyphicon-edit"></span> @ViewBag.Title</h2>
<hr />


@using (Html.BeginForm("Edit", "Mangas", FormMethod.Post, new { id = "formCrud" }))
{
    <div class="container-fluid">
        <div class="form-horizontal">
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GeneroId, "GeneroId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <input type="button" value="Confirmar" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

Supermercado/Views/Mangas/Index.cshtml
@{
    ViewBag.Title = "Listar Mangas";
}

<h2>@ViewBag.Title</h2>

<p>
    <a href="javascript:void(0)" data-action="Create" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Novo Manga
    </a>
</p>

<table id="gridDados" class="table table-striped">
    <thead>
        <tr>
            <th data-column-id="Titulo" data-order="asc">Título</th>
            <th data-column-id="Autor">Autor</th>
            <th data-column-id="Ano">Ano</th>
            <th data-column-id="Valor" data-formatter="Dinheiro">Valor</th>
            <th data-formatter="Acoes" data-sortable="false">Ações</th>
        </tr>
    </thead>
</table>

@section scripts{

    <script src="~/Scripts/toastr.js"></script>
    @Scripts.Render("~/bundles/jquerybootgrid")
    <script src="~/Scripts/projeto/ControlarGrid.js"></script>

    <script type="text/javascript">

        numeral.language("pt-br");

        var controller = "Mangas";

        var urlListar = "@Url.Action("Listar")";

        $(document).ready(configurarControles);

    </script>

}

@section estilos{

    <link href="~/Content/jquery.bootgrid.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
}