Supermercado/Controllers/LojasFisicasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Supermercado.AcessoDados;
using Supermercado.Models;
using System.Linq.Dynamic;

namespace Supermercado.Controllers
{
    public class LojasFisicasController : Controller
    {
        private readonly BancoContexto _db = new BancoContexto();

        // GET: LojaFisicas
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Listar(string searchPhrase, int current = 1, int rowCount = 5)
        {
            var chave = Request.Form.AllKeys.First(k => k.StartsWith("sort"));
            var ordenacao = Request[chave];
            var campo = chave.Replace("sort[", string.Empty).Replace("]", string.Empty);
            var lojasFisicas = _db.LojasFisicas.ToList();

            var total = lojasFisicas.Count();

            if (!string.IsNullOrWhiteSpace(searchPhrase))
            {
                lojasFisicas = lojasFisicas.FindAll(g => g.Estado.ToLower().Contains(searchPhrase.ToLower()));
            }

            string campoOrdenacao = $"{campo} {ordenacao}";

            var lojasFisicasPaginados = lojasFisicas.OrderBy(campoOrdenacao).Skip((current - 1) * rowCount).Take(rowCount);

            return Json(new
            {
                rows = lojasFisicasPaginados.ToList(),
                current,
                rowCount,
                total
            }
            , JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LojaFisica lojaFisica = _db.LojasFisicas.Find(id);
            if (lojaFisica == null)
            {
                return HttpNotFound();
            }
            return PartialView(lojaFisica);
        }

        // GET: LojaFisicas/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(LojaFisica lojaFisica)
        {
            if (ModelState.IsValid)
            {
                _db.LojasFisicas.Add(lojaFisica);
                _db.SaveChanges();
                return Json(new { resultado = true, message = "LojaFisica cadastrado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }
        }

        // GET: LojaFisicas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LojaFisica lojaFisica = _db.LojasFisicas.Find(id);
            if (lojaFisica == null)
            {
                return HttpNotFound();
            }
            return PartialView(lojaFisica);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(LojaFisica lojaFisica)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(lojaFisica).State = EntityState.Modified;
                _db.SaveChanges();

                return Json(new { resultado = true, message = "LojaFisica editado com sucesso" });
            }
            else
            {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, message = erros });
            }
        }

        // GET: LojaFisicas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LojaFisica lojaFisica = _db.LojasFisicas.Find(id);
            if (lojaFisica == null)
            {
                return HttpNotFound();
            }
            return PartialView(lojaFisica);
        }

        // POST: LojaFisicas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            try
            {
                LojaFisica lojaFisica = _db.LojasFisicas.Find(id);

                _db.LojasFisicas.Remove(lojaFisica);

                _db.SaveChanges();

                return Json(new { resultado = true, message = "LojaFisica excluído com sucesso" });
            }
            catch (Exception e)
            {
                return Json(new { resultado = false, message = e.Message });
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Supermercado/Views/LojasFisicas/Create.cshtml
@model Supermercado.Models.LojaFisica

@{
    ViewBag.Title = "Nova Loja Fisica";
}

<h2><span class="glyphicon glyphicon-plus"></span> @ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Create", "LojasFisicas", FormMethod.Post, new { id = "formCrud" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.CEP)
            @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Estado)
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Cidade)
            @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Telefone)
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group">
        <input type="button" value="Salvar" class="btn btn-primary btn-lg" />
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

<script src="~/Scripts/jquery-1.10.2.intellisense.js"></script>

<script>
    $('#CEP').change(function (e) {
        e.preventDefault();
        $("#Cidade").val('');
        $("#Estado").val('');

        var cep = $('#CEP').val().replace("-", "");

        $.getJSON("http://cep.republicavirtual.com.br/web_cep.php?cep=" + cep + "&formato=json", {}, function (data) {

            if (data.resultado_txt = 'sucesso - cep completo') {        
                $("#Cidade").val(data.cidade);
                $("#Estado").val(data.uf);
            }

        });

        

    });
</script>

Supermercado/Views/LojasFisicas/Delete.cshtml
@model Supermercado.Models.LojaFisica

@{
    ViewBag.Title = "Apagar";
}

<h2><span class="glyphicon glyphicon-remove"></span> @ViewBag.Title Loja Fisica</h2>
<hr />
<h3>Confirma a exclução dessa loja fisica?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CEP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CEP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>


    @using (Html.BeginForm($"Delete", $"LojasFisicas", FormMethod.Post, new { id = "formCrud" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="button" value="Confirmar" class="btn btn-danger" />
        </div>
    }
</div>

<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

Supermercado/Views/LojasFisicas/Details.cshtml
@model Supermercado.Models.LojaFisica


@{
    ViewBag.Title = "Detalhamento";
}

<h2><span class="glyphicon glyphicon-list"></span> Detalhamento</h2>


<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CEP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CEP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>
</div>

Supermercado/Views/LojasFisicas/Edit.cshtml
@model Supermercado.Models.LojaFisica

@{
    ViewBag.Title = "Editar Loja Fisica";
}

<h2><span class="glyphicon glyphicon-edit"></span> @ViewBag.Title</h2>
<hr />


@using (Html.BeginForm("Edit", "LojasFisicas", FormMethod.Post, new { id = "formCrud" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="row">

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.CEP)
            @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Estado)
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Cidade)
            @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-xs-8">
            @Html.LabelFor(model => model.Telefone)
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <input type="button" value="Confirmar" class="btn btn-primary btn-lg" />
    </div>
}


@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/projeto/EnviarFormulario.js"></script>

<script type="text/javascript">

    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

</script>

<script src="~/Scripts/jquery-1.10.2.intellisense.js"></script>

<script>
    $('#CEP').change(function (e) {
        e.preventDefault();
        $("#Cidade").val('');
        $("#Estado").val('');

        var cep = $('#CEP').val().replace("-", "");

        $.getJSON("http://cep.republicavirtual.com.br/web_cep.php?cep=" + cep + "&formato=json", {}, function (data) {

            if (data.resultado_txt = 'sucesso - cep completo') {
                $("#Cidade").val(data.cidade);
                $("#Estado").val(data.uf);
            }

        });
    });
</script>

Supermercado/Views/LojasFisicas/Index.cshtml
@{
    ViewBag.Title = "Listar Lojas Fisicas";
}

<p>
    <a href="javascript:void(0)" data-action="Create" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Nova Loja Fisica
    </a>
</p>

<table id="gridDados" class="table table-striped">
    <thead>
        <tr>
            <th data-column-id="Estado" data-order="asc">Estado</th>
            <th data-column-id="Cidade" data-order="asc">Cidade</th>
            <th data-column-id="CEP" data-order="asc">CEP</th>
            <th data-column-id="Telefone" data-order="asc">Telefone</th>
            <th data-formatter="Acoes" data-sortable="false">Ações</th>
        </tr>
    </thead>
</table>

@section scripts{

    <script src="~/Scripts/toastr.js"></script>
    @Scripts.Render("~/bundles/jquerybootgrid")
    <script src="~/Scripts/projeto/ControlarGrid.js"></script>

    <script type="text/javascript">

        numeral.language("pt-br");

        var controller = "LojasFisicas";

        var urlListar = "@Url.Action($"Listar")";

        $(document).ready(configurarControles);

    </script>

}

@section estilos{

    <link href="~/Content/jquery.bootgrid.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
}